/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Iterfaces;

import java.sql.Connection;
import tps.Conectar.Sentencias_sql;
import tps.Conectar.conexion;

/**
 *
 * @author usuario
 */
public final class Formato_Compra extends javax.swing.JFrame {

        
     
    /**
     * Creates new form Formato_Compra
     */
    public Formato_Compra() {
        initComponents();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Taller Diagnostico");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Producto_Compra = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Precio_Uni_Compra = new javax.swing.JTextField();
        Cantidad_Compra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Toatal_Compra = new javax.swing.JTextField();
        Button_Aceptar_Compra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        Producto_Compra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ZAPATO FORMAL", "ZAPATO DEPORTIVO", "ZAPATO INFORMAL", "PRENDA FORMAL", "PRENDA DEPORTIVA", "PRENDA INFORMAL" }));
        Producto_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producto_CompraActionPerformed(evt);
            }
        });
        getContentPane().add(Producto_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Precio Unidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        Precio_Uni_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_Uni_CompraActionPerformed(evt);
            }
        });
        getContentPane().add(Precio_Uni_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 80, 20));
        getContentPane().add(Cantidad_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("TOTAL COMPRA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        Toatal_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Toatal_CompraActionPerformed(evt);
            }
        });
        getContentPane().add(Toatal_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 80, -1));

        Button_Aceptar_Compra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_Aceptar_Compra.setText("Aceptar");
        Button_Aceptar_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Aceptar_CompraActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Aceptar_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TPS_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 314));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Producto_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producto_CompraActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_Producto_CompraActionPerformed

    private void Precio_Uni_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_Uni_CompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_Uni_CompraActionPerformed

    private void Toatal_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Toatal_CompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Toatal_CompraActionPerformed

    private void Button_Aceptar_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Aceptar_CompraActionPerformed
        // TODO add your handling code here: 
        String tipo,cantidad,id;
        System.out.print(Cantidad_Compra.getText());
        cantidad = Cantidad_Compra.getText();
        id = "0";
        tipo = Producto_Compra.getSelectedItem().toString();
       
        if (tipo == "ZAPATO FORMAL"){
            id = "01";
        }
      
        //Sentencias_sql compra = new Sentencias_sql();
        
    }//GEN-LAST:event_Button_Aceptar_CompraActionPerformed
  
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Aceptar_Compra;
    private javax.swing.JTextField Cantidad_Compra;
    private javax.swing.JTextField Precio_Uni_Compra;
    private javax.swing.JComboBox<String> Producto_Compra;
    private javax.swing.JTextField Toatal_Compra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
