/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Iterfaces;

/**
 *
 * @author usuario
 */
public class Formato_Venta extends javax.swing.JFrame {

    /**
     * Creates new form Formato_Venta
     */
    public Formato_Venta() {
        initComponents();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Taller Diagnostico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Aceptar_Venta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Toatal_Venta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Producto_Venta = new javax.swing.JComboBox<>();
        Precio_Uni_Venta = new javax.swing.JTextField();
        Cantidad_Venta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Aceptar_Venta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_Aceptar_Venta.setText("Aceptar");
        Button_Aceptar_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Aceptar_VentaActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Aceptar_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Precio Unidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        Toatal_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Toatal_VentaActionPerformed(evt);
            }
        });
        getContentPane().add(Toatal_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("TOTAL COMPRA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        Producto_Venta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ZAPATO FORMAL", "ZAPATO DEPORTIVO", "ZAPATO INFORMAL", "PRENDA FORMAL", "PRENDA DEPORTIVA", "PRENDA INFORMAL" }));
        Producto_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producto_VentaActionPerformed(evt);
            }
        });
        getContentPane().add(Producto_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Precio_Uni_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_Uni_VentaActionPerformed(evt);
            }
        });
        getContentPane().add(Precio_Uni_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, 20));
        getContentPane().add(Cantidad_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TPS_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 557, 317));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Producto_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producto_VentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Producto_VentaActionPerformed

    private void Precio_Uni_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_Uni_VentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_Uni_VentaActionPerformed

    private void Toatal_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Toatal_VentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Toatal_VentaActionPerformed

    private void Button_Aceptar_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Aceptar_VentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Aceptar_VentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formato_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formato_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formato_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formato_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formato_Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Aceptar_Venta;
    private javax.swing.JTextField Cantidad_Venta;
    private javax.swing.JTextField Precio_Uni_Venta;
    private javax.swing.JComboBox<String> Producto_Venta;
    private javax.swing.JTextField Toatal_Venta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
