/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Iterfaces;

/**
 *
 * @author usuario
 */
public class Interfaz_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Principal
     */
    public Interfaz_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Taller Diagnostico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jFrame1 = new javax.swing.JFrame();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        ButtonCompra = new javax.swing.JButton();
        ButtonVenta = new javax.swing.JButton();
        ButtonDevolucion = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonCompra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonCompra.setText("Compra");
        ButtonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCompraActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, -1));

        ButtonVenta.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        ButtonVenta.setText("Venta");
        ButtonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVentaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 120, -1));

        ButtonDevolucion.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        ButtonDevolucion.setText("Devolucion");
        ButtonDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDevolucionActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TPS_1.jpg"))); // NOI18N
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 552, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCompraActionPerformed
        // TODO add your handling code here:
        Formato_Compra obj = new Formato_Compra();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonCompraActionPerformed

    private void ButtonDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDevolucionActionPerformed

    private void ButtonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVentaActionPerformed
        // TODO add your handling code here:
        Formato_Venta obj = new Formato_Venta();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCompra;
    private javax.swing.JButton ButtonDevolucion;
    private javax.swing.JButton ButtonVenta;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
